---
name: Expo Review
on:
  push:
    branches:
      -main
    paths-ignore:
      - "README.md"
  workflow_dispatch:

jobs:
  preview:
    name: Expo Compatibility Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Latest Commit Author
        id: check-author
        run: |
          AUTHOR=$(git log -1 --pretty=format:'%an')
          echo "Latest commit author: $AUTHOR"
          echo "AUTHOR=$AUTHOR" >> $GITHUB_ENV

      - name: Skip if Merged by Bot
        run: |
          if [[ "${{ env.AUTHOR }}" == "github-actions[bot]" ]]; then
            echo "Skipping workflow because the commit was merged by a bot."
            exit 0
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPOTOKEN }}

      - name: Install dependencies
        run: |
          npm install
          npx expo install --fix

      - name: TypeScript Check
        run: npx tsc --noEmit

      - name: Run Expo Doctor
        run: npx expo-doctor

      - name: Verify Expo Config
        run: npx expo config
