# only runs when something is merged into main
---
name: "Auto Update README"

on:
  workflow_run:
    workflows: ["Expo Review"]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  preview:
    name: Update README
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'workflow_run' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main') ||
      (github.event_name == 'workflow_dispatch')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies
        run: |
          npm install
          npx expo install --fix

      - name: Run README Update Script
        run: npm run update-readme

      - name: Get Latest Commit Message
        id: last_commit
        run: |
          LATEST_MSG=$(git log -1 --pretty=format:%s)
          echo "LAST_COMMIT_MSG=$LATEST_MSG" >> $GITHUB_ENV

      - name: Check for Changes
        id: git_status
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
            echo "Changes detected, will create PR"
          else
            echo "CHANGES_DETECTED=false" >> $GITHUB_ENV
            echo "No changes detected, skipping PR creation"
          fi

      - name: Create Pull Request
        id: create-pull-request
        if: env.CHANGES_DETECTED == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto-update README for commit: ${{ env.LAST_COMMIT_MSG }}"
          branch: auto-update-readme-${{ github.run_id }}
          delete-branch: true
          title: "Auto-update README"
          body: |
            This PR updates the README automatically.
            
            Based on commit: ${{ env.LAST_COMMIT_MSG }}
          base: main
          labels: "auto-merge, README update"

      - name: Wait for Status Checks
        if: env.CHANGES_DETECTED == 'true' && steps.create-pull-request.outputs.pull-request-number != ''
        run: |
          PR_NUMBER="${{ steps.create-pull-request.outputs.pull-request-number }}"
          echo "Waiting for status checks to complete on PR #${PR_NUMBER}..."
          
          # Wait for up to 10 minutes (60 x 10 = 600 seconds)
          MAX_ATTEMPTS=60
          WAIT_SECONDS=10
          
          for ((i=1; i<=MAX_ATTEMPTS; i++)); do
            # Check if the "Expo Compatibility Check" is successful
            STATUS=$(gh pr view ${PR_NUMBER} --json statusCheckRollup --jq '.statusCheckRollup[] | select(.name=="Expo Compatibility Check") | .status')
            CONCLUSION=$(gh pr view ${PR_NUMBER} --json statusCheckRollup --jq '.statusCheckRollup[] | select(.name=="Expo Compatibility Check") | .conclusion')
            
            echo "Attempt $i/$MAX_ATTEMPTS - Status: $STATUS, Conclusion: $CONCLUSION"
            
            if [[ "$STATUS" == "COMPLETED" && "$CONCLUSION" == "SUCCESS" ]]; then
              echo "Status check passed successfully!"
              echo "STATUS_CHECKS_PASSED=true" >> $GITHUB_ENV
              break
            elif [[ "$CONCLUSION" == "FAILURE" || "$CONCLUSION" == "CANCELLED" ]]; then
              echo "Status check failed or was cancelled."
              echo "STATUS_CHECKS_PASSED=false" >> $GITHUB_ENV
              break
            else
              echo "Status check still pending. Waiting ${WAIT_SECONDS} seconds..."
              sleep ${WAIT_SECONDS}
            fi
            
            # If we've reached the max attempts and haven't broken out of the loop
            if [[ $i -eq $MAX_ATTEMPTS ]]; then
              echo "Timed out waiting for status checks to complete."
              echo "STATUS_CHECKS_PASSED=false" >> $GITHUB_ENV
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Verify PR Creation
        run: |
          if [[ "${{ env.CHANGES_DETECTED }}" == "true" && -z "${{ steps.create-pull-request.outputs.pull-request-number }}" ]]; then
            echo "::error::Failed to create PR despite changes being detected."
            exit 1
          elif [[ "${{ env.CHANGES_DETECTED }}" == "false" ]]; then
            echo "No changes detected. No PR needed."
          else
            echo "PR #${{ steps.create-pull-request.outputs.pull-request-number }} created successfully."
          fi

      - name: Auto-Merge the PR
        if: env.CHANGES_DETECTED == 'true' && steps.create-pull-request.outputs.pull-request-number != ''
        run: |
          gh pr merge ${{ steps.create-pull-request.outputs.pull-request-number }} --merge --admin --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}