# only runs when something is merged into main
---
name: "Auto Update README"

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install --no-package-lock
          npx expo install --fix

      - name: Run README Update Script
        run: npm run update-readme

      - name: Get Latest Commit Message
        id: last_commit
        run: |
          LATEST_MSG=$(git log -1 --pretty=format:%s)
          echo "LAST_COMMIT_MSG=$LATEST_MSG" >> $GITHUB_ENV

      - name: Pull Latest main
        run: |
          git config --global user.email \
            "github-actions[bot]@users.noreply.github.com"
          git config --global user.name \
            "github-actions[bot]"
          echo "pulling latest origin/main"
          git pull --rebase origin main || echo "No updates needed"

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: >
            Auto-update README for commit:
            ${{ env.LAST_COMMIT_MSG }}
          branch: main
