# only runs when something is merged into main
---
name: "Auto Update README"

on:
  workflow_run:
    workflows: ["Expo Review"]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: write

jobs:
  preview:
    name: Update README
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'workflow_run' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main') ||
      (github.event_name == 'workflow_dispatch')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Git User Identity
        run: |
          git config --global user.email \
            "github-actions[bot]@users.noreply.github.com"
          git config --global user.name \
            "github-actions[bot]"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies
        run: |
          npm install
          npx expo install --fix

      - name: Run README Update Script
        run: npm run update-readme

      - name: Git Diff for Test
        run: git diff -- README.md

      - name: Get Latest Commit Message
        id: last_commit
        run: |
          LATEST_MSG=$(git log -1 --pretty=format:%s)
          echo "LAST_COMMIT_MSG=$LATEST_MSG" >> $GITHUB_ENV

      - name: Fetch Latest Main
        run: |
          git fetch origin main

      - name: Check for Changes
        id: git_status
        run: |
          git add -A  # Stage all changes before checking
          if git diff --cached --exit-code; then
            echo "No changes to commit."
            echo "SKIP_PR=true" >> $GITHUB_ENV
          else
            echo "Changes detected, proceeding with commit."
            echo "SKIP_PR=false" >> $GITHUB_ENV
          fi

      - name: Commit and Push Changes to New Branch
        if: env.SKIP_PR == 'false'
        run: |
          git checkout -b auto-update-readme-${{ github.run_id }}
          git commit -m "Auto-update README for commit: \
            ${{ env.LAST_COMMIT_MSG }}"
          git push origin auto-update-readme-${{ github.run_id }}

      - name: Create Pull Request
        id: create_pr
        if: env.SKIP_PR == 'false'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: auto-update-readme-${{ github.run_id }}
          title: "Auto-update README"
          body: "This PR updates the README automatically."
          base: main
          labels: "auto-merge"
        run: echo "${{ steps.create_pr.outputs.pull-request-number }}"

      - name: Force PR Number Output
        run: |
          if [ -z "${{ steps.create_pr.outputs.pull-request-number }}" ]; then
            echo "No PR was created. Failing workflow."
            exit 1
          else
            echo "PR Created: \
              #${{ steps.create_pr.outputs.pull-request-number }}"
          fi

      - name: Auto-Merge the PR
        if: ${{ steps.create_pr.outputs.pull-request-number }}
        run: |
          gh pr merge ${{ steps.create_pr.outputs.pull-request-number }} \
          --merge --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
