---
name: "Auto Update README"

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-readme:
    name: "Update README"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies
        run: |
          npm install
          npx expo install --fix

      - name: Run README Update Script
        run: npm run update-readme

      - name: Get Latest Commit Message
        id: last_commit
        run: |
          LATEST_MSG=$(git log -1 --pretty=format:%s)
          echo "LAST_COMMIT_MSG=$LATEST_MSG" >> $GITHUB_ENV

      - name: Check for Changes
        id: git_status
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
            echo "Changes detected, proceeding with PR creation..."
          else
            echo "CHANGES_DETECTED=false" >> $GITHUB_ENV
            echo "No changes detected. Exiting."
            exit 0  # Exit successfully if no changes
          fi

      - name: Create Pull Request
        id: create-pr
        if: env.CHANGES_DETECTED == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT_GITHUB_ACTIONS }}
          commit-message: "Auto-update README for commit: ${{ env.LAST_COMMIT_MSG }}"
          branch: auto-update-readme-${{ github.run_id }}
          delete-branch: false
          title: "Auto-update README"
          assignees: "Nathanvititoe"
          body: |
            This PR updates
